# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# powerlevel9k settings.
# We don't need the branch icon because we have nerd fonts installed, so a
# github/mercurial icon is already displayed.
POWERLEVEL9K_HIDE_BRANCH_ICON=true
POWERLEVEL9K_MODE="nerdfont-complete"
POWERLEVEL9K_STATUS_OK=false
POWERLEVEL9K_VCS_SHORTEN_LENGTH=5
POWERLEVEL9K_VCS_SHORTEN_MIN_LENGTH=11
POWERLEVEL9K_VCS_SHORTEN_STRATEGY="truncate_middle"
POWERLEVEL9K_VCS_SHORTEN_DELIMITER=".."
POWERLEVEL9K_VI_COMMAND_MODE_STRING=$'\uE62B' # The vim icon.
POWERLEVEL9K_VI_INSERT_MODE_STRING=""

#POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=$'\uE0B1'
#POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=$'\uE0B1'

POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="green"
POWERLEVEL9K_DIR_ETC_BACKGROUND="black"
POWERLEVEL9K_DIR_ETC_FOREGROUND="green"
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="black"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="green"
POWERLEVEL9K_DIR_HOME_BACKGROUND="black"
POWERLEVEL9K_DIR_HOME_FOREGROUND="green"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="black"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="green"
POWERLEVEL9K_TIME_BACKGROUND="black"
POWERLEVEL9K_TIME_FOREGROUND="white"
POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND="yellow1"
POWERLEVEL9K_VI_MODE_NORMAL_FOREGROUND="black"
POWERLEVEL9K_VI_MODE_INSERT_BACKGROUND="black"
POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND="green"

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  vi_mode
  dir
)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  vcs
  virtualenv
  time
  status
)

# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="powerlevel9k/powerlevel9k"

# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  colored-man-pages
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source "$ZSH/oh-my-zsh.sh"

# Enable vim bindings.
bindkey -v

# Bind "jj" to exit edit mode.
bindkey 'jj' vi-cmd-mode

dir="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
[ -f "${HOME}/.fzf.zsh" ] && source "${HOME}/.fzf.zsh"
source "$dir/../sh_common/rc"
