#!/bin/bash
dir="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
source "${dir}/prompt.sh"

[ -f "${HOME}/.fzf.bash" ] && source "${HOME}/.fzf.bash"

# User completion files
if [ -n "$(ls ~/.bash_completion.d)" ]; then
  for comp_file in ~/.bash_completion.d/* ; do
    source "${comp_file}"
  done
fi

# NOTE: This also sets dir, so do it after setting the prompt above.
source "${dir}/../sh_common/rc"

eval "$("${HOME}/.local/bin/mise" activate bash)"
