#!/bin/bash
dir="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
source "${dir}/prompt.sh"

# shellcheck disable=SC1091
[ -f "${HOME}/.fzf.bash" ] && source "${HOME}/.fzf.bash"

# User completion files
if [ -n "$(ls ~/.bash_completion.d)" ]; then
  for comp_file in ~/.bash_completion.d/*; do
    source "${comp_file}"
  done
fi

# NOTE: This also sets dir, so do it after setting the prompt above.
source "${dir}/../sh_common/rc"

eval "$("${HOME}/.local/bin/mise" activate bash)"

# Shortcut to open yazi and change to current directory after exiting.
function yy() {
  local tmp
  tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
  yazi "$@" --cwd-file="$tmp"
  if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
    # shellcheck disable=SC2164
    cd -- "$cwd"
  fi
  rm -f -- "$tmp"
}
